# TASK 1

## 1. Write a function to compute 5/0 and use try/except to catch the exceptions

In [7]:
def compute(a,b):
    try:
        value= a/b
    except ZeroDivisionError as e:
        return (f'{e} has occured')
    else:
        return (f'value of {a}/{b} : {value}')
    finally:
        print ("finally is executed")


print(compute(5,0))


finally is executed
division by zero has occured


## 2 . Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 

In [10]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"] 

def sentences(subjects,verbs,objects):
    for sub in subjects:
        for verb in verbs:
            for obj in objects:
                print(sub,verb,obj)
   

sentences(subjects,verbs,objects)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# TASK 2

## 1 . Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.

In [24]:
import numpy as np
def rowpow(a,n):
    l=[]
    for i in range(0,n):
        l.append(a**(n-i-1))
    return l
def power(input_list):
    n=len(input_list)
    result = [rowpow(i,n) for i in input_list]
    return result
    
input_list=list(map(int,input("enter ur list items : ").strip().split()))
ar=power(input_list)
ar1=np.array(ar)
print(ar1)

enter ur list items : 1 2 3 4 5
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
